import { slug } from './utils.js';
const finding = (id, severity, message, detail, options = {}) => ({ id, ruleId: id, severity, message, detail, nodeIds: options.nodeIds || [], suggestion: options.suggestion });
function indexStatement(table, column) { return `CREATE INDEX idx_${slug(table)}_${slug(column)} ON ${table} (${column});`; }
export function runRules(bound, catalog, plan) {
  const findings = [];
  for (const scan of plan.scans) { const filter = bound.ast.predicates.find(item => item.table === scan.table); if (scan.access === 'Seq' && filter && catalog[scan.table].rowCount >= 10000) { const estimated = catalog[scan.table].rowCountSource === 'default estimate'; findings.push(finding('full-table-scan', 'critical', `Full scan on ${scan.table}`, `${estimated ? 'About ' : ''}${catalog[scan.table].rowCount.toLocaleString()} ${estimated ? 'estimated ' : ''}rows are read to apply ${filter.raw}.`, { nodeIds: [scan.id], suggestion: filter.sargable ? { kind: 'index', sql: indexStatement(scan.table, filter.column), rationale: `An index on ${scan.table}.${filter.column} lets PostgreSQL seek matching rows instead of reading the whole table.` } : undefined })); }
  for (const predicate of bound.ast.predicates) { if (predicate.function) findings.push(finding('non-sargable-predicate', 'warning', 'Function prevents index use', `${predicate.function.toUpperCase()}(${predicate.column}) makes a normal index unusable.`, { suggestion: { kind: 'rewrite', sql: predicate.raw.replace(new RegExp(`${predicate.function}\\(([^)]+)\\)`, 'i'), '$1'), rationale: 'Compare the bare column or add a matching expression index.' } })); if (predicate.leadingWildcard) findings.push(finding('leading-wildcard-like', 'warning', 'Leading wildcard disables a B-tree index', 'A pattern beginning with % cannot use a normal B-tree prefix search.')); }
  for (const join of bound.ast.joins) { if (!join.pair) continue; const indexed = join.pair.some(item => catalog[bound.aliases[item.alias]]?.indexes.some(index => index.columns[0] === item.column)); if (!indexed) { const target = join.pair[0]; const table = bound.aliases[target.alias]; findings.push(finding('unindexed-join', 'critical', 'Join has no supporting index', `${table}.${target.column} is probed without an index.`, { suggestion: { kind: 'index', sql: indexStatement(table, target.column), rationale: 'An index on the join key reduces repeated scan work.' } })); } }
  if (bound.ast.hasStar) findings.push(finding('select-star', 'info', 'SELECT * returns more data than needed', 'Choose only the columns the application reads to reduce I/O and network work.'));
  if (bound.ast.cartesian) findings.push(finding('cartesian-product', 'critical', 'Possible Cartesian product', 'Multiple tables are listed without a JOIN condition.'));
  return findings;
}
